apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: varshat99/myimg1:latest
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30080
